initialSetup/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
    OR(
        MONTH(TODAY()) &lt; MONTH(DOB__c),
        AND(
            MONTH(TODAY()) = MONTH(DOB__c),
            DAY(TODAY()) &lt; DAY(DOB__c)
        )
    ),
    YEAR(TODAY()) - YEAR(DOB__c) - 1,
    YEAR(TODAY()) - YEAR(DOB__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Blood_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Blood_Pressure__c</fullName>
    <label>Blood Pressure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/Account/fields/BMI__c.field-meta.xml
<CustomField>
    <fullName>BMI__c</fullName>
    <formula>IF(
    AND(NOT(ISBLANK(Weight__c)), NOT(ISBLANK(Height__c)), Height__c &gt; 0),
    Weight__c / ((Height__c / 100) ^ 2),
    NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BMI (Body Mass Index)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

initialSetup/main/default/objects/Account/fields/ECG_Status__c.field-meta.xml
<CustomField>
    <fullName>ECG_Status__c</fullName>
    <label>ECG Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Abnormal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Account/fields/Hepatic_Function__c.field-meta.xml
<CustomField>
    <fullName>Hepatic_Function__c</fullName>
    <label>Hepatic Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Abnormal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Account/fields/Masked_Name__c.field-meta.xml
<CustomField>
    <fullName>Masked_Name__c</fullName>
    <label>Masked Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/Account/fields/Medical_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Medical_Specialty__c</fullName>
    <label>Medical Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Account/fields/Sugar_Status__c.field-meta.xml
<CustomField>
    <fullName>Sugar_Status__c</fullName>
    <label>Sugar Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight (kg)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

initialSetup/main/default/objects/Account/recordTypes/CRO.recordType-meta.xml
<RecordType>
    <fullName>CRO</fullName>
    <active>true</active>
    <label>CRO</label>
</RecordType>

initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/CRO_Account__c.field-meta.xml
<CustomField>
    <fullName>CRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO_Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CRO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Research_Study__c.field-meta.xml
<CustomField>
    <fullName>Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Study</label>
    <referenceTo>Research_Study__c</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Research_Study__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO Research Study</label>
    <referenceTo>CRO_Research_Study__c</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <referenceTo>HealthcareFacility</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/Enrolled_Site_Research_Candidate__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site Research Candidate</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Enrolled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site Research Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/CRO_Agent_Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>CRO_Agent_Prompt_Response__c</fullName>
    <label>CRO Agent Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Eligibility_Score__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Score__c</fullName>
    <label>Eligibility Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site__c</fullName>
    <label>Enrolled Site</label>
    <referenceTo>Enrolled_Site__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site_Research_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Research_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolled Site Research Candidate</label>
    <referenceTo>Enrolled_Site_Research_Candidate__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Has_Eligibility_Score__c.field-meta.xml
<CustomField>
    <fullName>Has_Eligibility_Score__c</fullName>
    <formula>NOT(ISBLANK(Eligibility_Score__c))</formula>
    <label>Has Eligibility Score</label>
    <type>Checkbox</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolled_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/PCP__c.field-meta.xml
<CustomField>
    <fullName>PCP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PCP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates (PCP)</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/PCP_Agent_LLM_Response__c.field-meta.xml
<CustomField>
    <fullName>PCP_Agent_LLM_Response__c</fullName>
    <label>PCP Agent LLM Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/PCP_Agent_Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>PCP_Agent_Prompt_Response__c</fullName>
    <label>PCP Agent Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Site_Agent_LLM_Response__c.field-meta.xml
<CustomField>
    <fullName>Site_Agent_LLM_Response__c</fullName>
    <label>Site Agent LLM Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Site_Agent_Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>Site_Agent_Prompt_Response__c</fullName>
    <label>Site Agent Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Initial Check</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Trial In-Progress</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Initial Check Cleared</fullName>
            </value>
            <value>
                <fullName>Rejected After Shortlisted</fullName>
            </value>
            <value>
                <fullName>Initial Check Failed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Invite Sent for Enrollment</fullName>
            </value>
            <value>
                <fullName>Enrollment Accepted</fullName>
            </value>
            <value>
                <fullName>Enrollment Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Enrolled</fullName>
    <active>true</active>
    <label>Enrolled</label>
</RecordType>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Pre_Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Pre_Enrolled</fullName>
    <active>true</active>
    <label>Pre-Enrolled</label>
</RecordType>

initialSetup/main/default/objects/Research_Study__c/Research_Study__c.object-meta.xml
<CustomObject>
    <label>Research Study</label>
    <nameField>
        <label>Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Research_Study__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/classes/ClinicalTrialWrapperController.cls
/**
* @File Name : ClinicalTrialWrapperController.cls
* @Description : 
* @Author : Nitin Karan;
* @Last Modified On : August 21, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | August 21, 2025 | Nitn Karan  | Initial Version
**/

public with sharing class ClinicalTrialWrapperController {
 
    @AuraEnabled
    public static List<ClinicalTrialWrapperService.RSWrapper> getResearchStudyDetails(Id researchStudyId,List<Id> selectedCROs) {
 
        List<ClinicalTrialWrapperService.RSWrapper> rsWrapperList = new List<ClinicalTrialWrapperService.RSWrapper>();
 
        Research_Study__c rs = [SELECT Id, Name, Status__c FROM Research_Study__c WHERE Id = :researchStudyId LIMIT 1];
 
        ClinicalTrialWrapperService.RSWrapper rsWrapper = new ClinicalTrialWrapperService.RSWrapper();
        rsWrapper.id = rs.Id;
        rsWrapper.name = rs.Name;
        rsWrapper.status = rs.Status__c;
        rsWrapper.cssClass = 'RSWrapper_' + (rs.Status__c != null ? rs.Status__c.replaceAll('\\s','') : 'Unknown');
        rsWrapper.resStudy = rs;
        rsWrapper.croWrapperList = new List<ClinicalTrialWrapperService.CROWrapper>();
 
        // Fetch CRO Research Studies with Enrolled Sites
        List<CRO_Research_Study__c> croList = [
            SELECT Id, Status__c, CRO_Account__c, CRO_Account__r.Name,
                   (SELECT Id, Name,Status__c, Healthcare_Facility__c, Healthcare_Facility__r.Name 
                    FROM Enrolled_Site__r
                    WHERE CRO_Research_Study__c != null ORDER BY Status__c ) 
            FROM CRO_Research_Study__c
            WHERE Research_Study__c = :rs.Id AND CRO_Account__c IN :selectedCROs];
        //AND Status__c = 'Identified'
 
        // Preload all candidates with patient info
        List<Enrolled_Site_Research_Candidate__c> allCandidates = [
                                    SELECT Id, Name,Eligibility_Score__c, Has_Eligibility_Score__c,Patient__r.Sugar_Status__c,
                                     Status__c, Site_Agent_Prompt_Response__c,PCP_Agent_Prompt_Response__c, 
                                     CRO_Agent_Prompt_Response__c, PCP__c,Patient__c, Patient__r.Masked_Name__c ,Patient__r.Age__c,Patient__r.Weight__c,Patient__r.BMI__c,Patient__r.Blood_Pressure__c,Patient__r.ECG_Status__c ,Patient__r.Hepatic_Function__c
                                     FROM Enrolled_Site_Research_Candidate__c 
                                     WHERE Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c = :rs.Id 
                                     AND RecordType.DeveloperName IN('Pre_Enrolled','Enrolled')  AND Status__c In ('Invite Sent for Enrollment' ,'On Hold', 'Rejected After Shortlisted','Shortlisted','Initial Check','Initial Check Cleared','Initial Check Failed','Enrollment Accepted','Enrollment Rejected','Trial Complete','Trial In-Progress','Rejected','Enrolled') ORDER BY RecordType.DeveloperName ASC, Has_Eligibility_Score__c DESC, Eligibility_Score__c DESC]; //Site_Agent_LLM_Response__c,PCP_Agent_LLM_Response__c

                             
 
 
        // Map PCP Id -> List of candidates
        Map<Id, List<Enrolled_Site_Research_Candidate__c>> pcpToCandidateMap = new Map<Id, List<Enrolled_Site_Research_Candidate__c>>();
        for(Enrolled_Site_Research_Candidate__c cand : allCandidates){
            System.debug('age>> ' + cand.Patient__r.Weight__c);
            if(cand.PCP__c != null){
                
                if(!pcpToCandidateMap.containsKey(cand.PCP__c)){
                    pcpToCandidateMap.put(cand.PCP__c, new List<Enrolled_Site_Research_Candidate__c>());
                }
                pcpToCandidateMap.get(cand.PCP__c).add(cand);
            }
        }
 
        for(CRO_Research_Study__c cro : croList) {
            ClinicalTrialWrapperService.CROWrapper croWrapper = new ClinicalTrialWrapperService.CROWrapper();
            croWrapper.croId = cro.CRO_Account__c;
            croWrapper.croName = cro.CRO_Account__r.Name;
            croWrapper.status = cro.Status__c;
            croWrapper.researchStudyId = rs.Id;
            croWrapper.cssClass = 'CROWrapper_' + (cro.Status__c != null ? cro.Status__c.replaceAll('\\s','') : 'Unknown');
            croWrapper.hfWrapperList = new List<ClinicalTrialWrapperService.HFWrapper>();
            croWrapper.hasChildren = cro.Enrolled_Site__r.size() > 0;
            croWrapper.isExpanded = false;
 
            Map<Id, List<Enrolled_Site__c>> hfToSitesMap = new Map<Id, List<Enrolled_Site__c>>();
            for(Enrolled_Site__c site : cro.Enrolled_Site__r) {
                if(site.Healthcare_Facility__c != null) {
                    if(!hfToSitesMap.containsKey(site.Healthcare_Facility__c)) {
                        hfToSitesMap.put(site.Healthcare_Facility__c, new List<Enrolled_Site__c>());
                    }
                    hfToSitesMap.get(site.Healthcare_Facility__c).add(site);
                }
            }
 
            for(Id hfId : hfToSitesMap.keySet()) {
                ClinicalTrialWrapperService.HFWrapper hfWrapper = new ClinicalTrialWrapperService.HFWrapper();
                hfWrapper.hfId = hfId;
                Enrolled_Site__c firstSite = hfToSitesMap.get(hfId)[0];
                hfWrapper.hfName = firstSite.Healthcare_Facility__r != null ? firstSite.Healthcare_Facility__r.Name : 'Unknown HF';
                hfWrapper.isIdentified = (firstSite.Status__c == 'Identified');
                hfWrapper.status = firstSite.Status__c;
                hfWrapper.cssClass = hfWrapper.status == 'Identified' ? 'hf-green' : 'hf-grey';
                hfWrapper.pcpWrapperList = new List<ClinicalTrialWrapperService.PCPWrapper>();
                hfWrapper.hasChildren = true;
                hfWrapper.isExpanded = false;
 
                List<Account> pcpList = [
                    SELECT Id, Name, Salutation,Medical_Specialty__c, Trial_Site__c
                    FROM Account
                    WHERE Trial_Site__c = :hfId
                ];
 
                for(Account pcp : pcpList) {
                    ClinicalTrialWrapperService.PCPWrapper pcpWrapper = new ClinicalTrialWrapperService.PCPWrapper();
                    pcpWrapper.id = pcp.Id;
                    pcpWrapper.name = 'Dr. ' + pcp.Name;
                    pcpWrapper.status = '';
                    pcpWrapper.researchStudyId = rs.Id;
                    pcpWrapper.healthcareFacilityId = hfId;
                    pcpWrapper.elCandidateWrapperList = new List<ClinicalTrialWrapperService.ELCandidateWrapper>();
                    pcpWrapper.hasChildren = pcpToCandidateMap.containsKey(pcp.Id) && pcpToCandidateMap.get(pcp.Id).size() > 0;
                    pcpWrapper.isExpanded = false;
                    pcpWrapper.cssClass = 'PCPWrapper_' + (pcpWrapper.status != null ? pcpWrapper.status.replaceAll('\\s','') : 'Unknown');
 
                    if(pcpToCandidateMap.containsKey(pcp.Id)){
                        Set<Id> patientIds = new Set<Id>();
                        for(Enrolled_Site_Research_Candidate__c cand : pcpToCandidateMap.get(pcp.Id)){
                            if(!patientIds.contains(cand.Patient__c)){
                                patientIds.add(cand.Patient__c);
                                
                                ClinicalTrialWrapperService.ELCandidateWrapper elWrapper = new ClinicalTrialWrapperService.ELCandidateWrapper();
                                elWrapper.idEnrolled = cand.Id;
                                elWrapper.name = cand.Name;
                                elWrapper.patientName = cand.Patient__r != null ? cand.Patient__r.Masked_Name__c : 'Unknown Patient';  
                                elWrapper.statusEnrolled = cand.Status__c;
                                elWrapper.patientAge = cand.Patient__r != null ? cand.Patient__r.Age__c : null ;
                                elWrapper.patientBMI = cand.Patient__r != null ? cand.Patient__r.BMI__c : null ;
                                elWrapper.patientBP = cand.Patient__r != null ? cand.Patient__r.Blood_Pressure__c : null ;
                                elWrapper.patientEcgStatus = cand.Patient__r != null ? cand.Patient__r.ECG_Status__c : null ;
                                elWrapper.patientHepaticFunction = cand.Patient__r != null ? cand.Patient__r.Hepatic_Function__c : null ;
                                elWrapper.patientWeight = cand.Patient__r != null ? cand.Patient__r.Weight__c : null ;
                                elWrapper.score = cand.Eligibility_Score__c;
                                elWrapper.siteLLMResponse = cand.Site_Agent_Prompt_Response__c;
                                elWrapper.pcpLLMResponse = cand.PCP_Agent_Prompt_Response__c;
                                elWrapper.croLLMResponse = cand.CRO_Agent_Prompt_Response__c;
                                elWrapper.researchStudyId = rs.Id;
                                elWrapper.pcpId = pcp.Id;
                                elWrapper.sugarStatus = cand.patient__r.Sugar_Status__c;
                                // elWrapper.cssClass = 'ELCandidateWrapper_' + (elWrapper.statusEnrolled != null ? elWrapper.statusEnrolled.replaceAll('\\s','') : 'Unknown');
                                String baseClass = 'flow-box txt-16';
                                switch on cand.Status__c {
                                    when 'Invite Sent for Enrollment' {
                                        elWrapper.cssClass = baseClass + ' pt-green';
                                    }
                                    when 'On Hold' {
                                        elWrapper.cssClass = baseClass + ' pt-orange';
                                    }
                                    when 'Rejected' {
                                        elWrapper.cssClass = baseClass + ' pt-red';
                                    }
                                    when 'Rejected After Shortlisted' {
                                        elWrapper.cssClass = baseClass + ' pt-mauve';
                                    }
                                    when 'Shortlisted' {
                                        elWrapper.cssClass = baseClass + ' pt-teal';
                                    }
                                    when 'Initial Check' {
                                        elWrapper.cssClass = baseClass + ' pt-blue';
                                    }
                                    when 'Initial Check Cleared' {
                                        elWrapper.cssClass = baseClass + ' pt-lime';
                                    }
                                    when 'Initial Check Failed' {
                                        elWrapper.cssClass = baseClass + ' pt-coral';
                                    }
                                    when 'Enrollment Accepted' {
                                        elWrapper.cssClass = baseClass + ' pt-accepted';
                                    }
                                    when 'Enrollment Rejected' {
                                        elWrapper.cssClass = baseClass + ' pt-amber';
                                    }
                                    when else {
                                        elWrapper.cssClass = baseClass; // fallback
                                    }
                                }
                                pcpWrapper.elCandidateWrapperList.add(elWrapper);
                            }
                        }
                        pcpWrapper.elCandidateWrapperList.sort(new ELCandidateStatusComparator());
                    }
 
                    hfWrapper.pcpWrapperList.add(pcpWrapper);
                }
 
                croWrapper.hfWrapperList.add(hfWrapper);
            }
 
            rsWrapper.croWrapperList.add(croWrapper);
        }
 
        rsWrapperList.add(rsWrapper);
        return rsWrapperList;
    }
    
    public class ELCandidateStatusComparator implements System.Comparator<ClinicalTrialWrapperService.ELCandidateWrapper> {
        Map<String, Integer> orderMap = new Map<String, Integer>{
            'Enrollment Accepted' => 1,
                'Enrollment Rejected' => 2,
                'Invite Sent for Enrollment' => 3,
                'On Hold' => 4,
                'Rejected After Shortlisted' => 5,
                'Shortlisted' => 6,
                'Rejected' => 7,
                'Initial Check Cleared' => 8,
                'Initial Check Failed' => 9,
                'Initial Check' => 10
                };
                    
                    public Integer compare(ClinicalTrialWrapperService.ELCandidateWrapper elA,
                                           ClinicalTrialWrapperService.ELCandidateWrapper elB) {
                                               Integer orderA = orderMap.containsKey(elA.statusEnrolled) ? orderMap.get(elA.statusEnrolled) : 999;
                                               Integer orderB = orderMap.containsKey(elB.statusEnrolled) ? orderMap.get(elB.statusEnrolled) : 999;
                                               
                                               if (orderA == orderB) {
                                                   // tie-breaker → higher score first
                                                   if (elA.score == elB.score) return 0;
                                                   return elA.score > elB.score ? -1 : 1;
                                               }
                                               return orderA < orderB ? -1 : 1;
                                           }
    }

}