initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/CRO_Account__c.field-meta.xml
<CustomField>
    <fullName>CRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO_Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CRO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Research_Study__c.field-meta.xml
<CustomField>
    <fullName>Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Study</label>
    <referenceTo>Research_Study__c</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Research_Study__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO Research Study</label>
    <referenceTo>CRO_Research_Study__c</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/Enrolled_Site_Research_Candidate__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site Research Candidate</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Enrolled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site Research Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/CRO_Agent_Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>CRO_Agent_Prompt_Response__c</fullName>
    <label>CRO Agent Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Eligibility_Score__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Score__c</fullName>
    <label>Eligibility Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site__c</fullName>
    <label>Enrolled Site</label>
    <referenceTo>Enrolled_Site__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site_Research_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Research_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolled Site Research Candidate</label>
    <referenceTo>Enrolled_Site_Research_Candidate__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolled_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/PCP_Agent_Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>PCP_Agent_Prompt_Response__c</fullName>
    <label>PCP Agent Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Site_Agent_Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>Site_Agent_Prompt_Response__c</fullName>
    <label>Site Agent Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Initial Check</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Trial In-Progress</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Initial Check Cleared</fullName>
            </value>
            <value>
                <fullName>Rejected After Shortlisted</fullName>
            </value>
            <value>
                <fullName>Initial Check Failed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Invite Sent for Enrollment</fullName>
            </value>
            <value>
                <fullName>Enrollment Accepted</fullName>
            </value>
            <value>
                <fullName>Enrollment Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Patient_Eligibility_Run_Log__c/Patient_Eligibility_Run_Log__c.object-meta.xml
<CustomObject>
    <label>Patient Eligibility Run Log</label>
    <nameField>
        <displayFormat>PELR-{000000}</displayFormat>
        <label>Patient Eligibility Run Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Eligibility Run Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Patient_Eligibility_Run_Log__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <label>Agent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Site Agent</fullName>
            </value>
            <value>
                <fullName>PCP Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Patient_Eligibility_Run_Log__c/fields/Enrolled_Site_Research_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Research_Candidate__c</fullName>
    <label>Enrolled Site Research Candidate</label>
    <referenceTo>Enrolled_Site_Research_Candidate__c</referenceTo>
    <relationshipLabel>Patient Eligibility Run Logs</relationshipLabel>
    <relationshipName>Patient_Eligibility_Run_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Patient_Eligibility_Run_Log__c/fields/Prompt_Response__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Response__c</fullName>
    <label>Prompt Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Research_Study__c/Research_Study__c.object-meta.xml
<CustomObject>
    <label>Research Study</label>
    <nameField>
        <label>Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Research_Study__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/classes/PatientAgentHeadlessController.cls
public class PatientAgentHeadlessController {
    
    public static void invokePDFPrompt(ContentDocument doc){
        //invoke prompt
    }
    public static void checkPatientSiteEligibility(Enrolled_Site_Research_Candidate__c enrolledSiteResearchCandidate, Account patient){
        
        Research_Study__c researchStudy = new Research_Study__c(Id = enrolledSiteResearchCandidate.Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c);      
        ConnectApi.WrappedValue inputResearchStudy = new ConnectApi.WrappedValue();
        inputResearchStudy.value = new Map<String, String> {'Id' => researchStudy.Id};
            
        ConnectApi.WrappedValue inputPatient = new ConnectApi.WrappedValue();
        inputPatient.value = new Map<String, String> {'Id' => patient.Id};
            
        Map<String, ConnectApi.WrappedValue> inputParams = new Map<String, ConnectApi.WrappedValue>{};
        inputParams.put('Input:Patient_Account',inputPatient);
        inputParams.put('Input:Research_Study',inputResearchStudy);
        
        String result = PromptUtility.invokePrompt('Patient_Eligibility', inputParams);
        result = result.replace('\u00A0', ' '); 
        
        //write log run logic here 
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(result);
        // Cast values if you need them as String
        String response = (String) resultMap.get('Response');
        String status = (String) resultMap.get('Status');
        
        Enrolled_Site_Research_Candidate__c enrolledSiteCandidate = new Enrolled_Site_Research_Candidate__c(Id=enrolledSiteResearchCandidate.Id,Status__c = status,Site_Agent_Prompt_Response__c = response);
        update enrolledSiteCandidate;
        Patient_Eligibility_Run_Log__c log = new Patient_Eligibility_Run_Log__c(Prompt_Response__c = response,Agent__c = 'Site Agent', Enrolled_Site_Research_Candidate__c = enrolledSiteCandidate.Id);
        insert log;
        System.debug(log);
        System.debug(enrolledSiteCandidate);
        
    } 
    
    public static void checkPatientPCPEligibility(Enrolled_Site_Research_Candidate__c enrolledSiteCandidate,Account patient){
        System.debug('Rashi');
        Research_Study__c researchStudy = new Research_Study__c(Id = enrolledSiteCandidate.Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c);
        ConnectApi.WrappedValue inputPatient = new ConnectApi.WrappedValue();
        inputPatient.value = new Map<String, String> {'Id' => patient.Id};
            
        ConnectApi.WrappedValue inputResearchStudy = new ConnectApi.WrappedValue();
        inputResearchStudy.value = new Map<String, String> {'Id' => researchStudy.Id};
            
        Map<String, ConnectApi.WrappedValue> inputParams = new Map<String, ConnectApi.WrappedValue>{};
        inputParams.put('Input:Patient',inputPatient);
        inputParams.put('Input:Research_Study',inputResearchStudy);
        System.debug('Rashi');
        String result = PromptUtility.invokePrompt('Patient_Shortlisting', inputParams);
        result = result.replace('\u00A0', ' ');
        System.debug('Rashi');
        //write log run logic here 
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(result);
        // Cast values if you need them as String
        String response = (String) resultMap.get('Response');
        String status = (String) resultMap.get('Status');
        
        enrolledSiteCandidate = new Enrolled_Site_Research_Candidate__c(Id = enrolledSiteCandidate.Id,Status__c = status,PCP_Agent_Prompt_Response__c = response);
        update enrolledSiteCandidate;
        Patient_Eligibility_Run_Log__c log = new Patient_Eligibility_Run_Log__c(Prompt_Response__c = response,Agent__c = 'PCP Agent', Enrolled_Site_Research_Candidate__c = enrolledSiteCandidate.Id);
        insert log;      
    }
    
    public static void patientPreferenceScorePromptInvoke(Enrolled_Site_Research_Candidate__c enrolledSiteCandidate){
        
        //Research_Study__c researchStudy = new Research_Study__c(Id = enrolledSiteCandidate.Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c);
        ConnectApi.WrappedValue inputPatient = new ConnectApi.WrappedValue();
        inputPatient.value = new Map<String, String> {'Id' => enrolledSiteCandidate.Patient__c};
            
        ConnectApi.WrappedValue inputResearchStudy = new ConnectApi.WrappedValue();
        //inputResearchStudy.value = new Map<String, String> {'Id' => researchStudy.Id};
        inputResearchStudy.value = new Map<String, String> {'Id' => enrolledSiteCandidate.Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c};
            
        ConnectApi.WrappedValue inputEnrolledCandidate = new ConnectApi.WrappedValue();
        inputEnrolledCandidate.value = new Map<String, String> {'Id' => enrolledSiteCandidate.Id};
            
        Map<String, ConnectApi.WrappedValue> inputParams = new Map<String, ConnectApi.WrappedValue>{};
        inputParams.put('Input:Patient_Account',inputPatient);
        inputParams.put('Input:ResearchStudy',inputResearchStudy);
        inputParams.put('Input:EnrolledCandidate',inputEnrolledCandidate);
        
        String result = PromptUtility.invokePrompt('Patient_Preference_Score', inputParams);
        System.debug('**Result***'+result);
        result = result.replace('\u00A0', ' ');
        
        //write log run logic here 
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(result);
        // Cast values if you need them as String
        String response = (String) resultMap.get('Response');
        Integer score = (Integer) resultMap.get('Score');
        System.debug(score);
        enrolledSiteCandidate = new Enrolled_Site_Research_Candidate__c(Id = enrolledSiteCandidate.Id,Eligibility_Score__c=score,CRO_Agent_Prompt_Response__c=response);
        update enrolledSiteCandidate;	
    }
}