initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/CRO_Account__c.field-meta.xml
<CustomField>
    <fullName>CRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO_Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CRO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Research_Study__c.field-meta.xml
<CustomField>
    <fullName>Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Study</label>
    <referenceTo>Research_Study__c</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Research_Study__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO Research Study</label>
    <referenceTo>CRO_Research_Study__c</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <referenceTo>HealthcareFacility</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/Enrolled_Site_Research_Candidate__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site Research Candidate</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Enrolled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site Research Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site__c</fullName>
    <label>Enrolled Site</label>
    <referenceTo>Enrolled_Site__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site_Research_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Research_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolled Site Research Candidate</label>
    <referenceTo>Enrolled_Site_Research_Candidate__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolled_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Initial Check</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Trial In-Progress</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Initial Check Cleared</fullName>
            </value>
            <value>
                <fullName>Rejected After Shortlisted</fullName>
            </value>
            <value>
                <fullName>Initial Check Failed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Invite Sent for Enrollment</fullName>
            </value>
            <value>
                <fullName>Enrollment Accepted</fullName>
            </value>
            <value>
                <fullName>Enrollment Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Enrolled</fullName>
    <active>true</active>
    <label>Enrolled</label>
</RecordType>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Pre_Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Pre_Enrolled</fullName>
    <active>true</active>
    <label>Pre-Enrolled</label>
</RecordType>

initialSetup/main/default/objects/Research_Study__c/Research_Study__c.object-meta.xml
<CustomObject>
    <label>Research Study</label>
    <nameField>
        <label>Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Research_Study__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Task/recordTypes/CRO_Agent_Task.recordType-meta.xml
<RecordType>
    <fullName>CRO_Agent_Task</fullName>
    <active>true</active>
    <label>CRO Agent Task</label>
</RecordType>

initialSetup/main/default/objects/Task/recordTypes/PCP_Agent_Task.recordType-meta.xml
<RecordType>
    <fullName>PCP_Agent_Task</fullName>
    <active>true</active>
    <label>PCP Agent Task</label>
</RecordType>

initialSetup/main/default/objects/Task/recordTypes/Site_Agent_Task.recordType-meta.xml
<RecordType>
    <fullName>Site_Agent_Task</fullName>
    <active>true</active>
    <label>Site Agent Task</label>
</RecordType>

initialSetup/main/default/classes/PatientEligibilityPromptCallBatch.cls
public class PatientEligibilityPromptCallBatch implements Database.Batchable<SObject>,Database.Stateful {
    
    private Id enrolledSiteId;
    private Enrolled_Site__c enrolledSiteRecord;
    private Boolean isPreliminaryCheck = false;
    
    public PatientEligibilityPromptCallBatch(Id enrolledSiteId, Boolean isPreliminaryCheck) {
        this.isPreliminaryCheck = isPreliminaryCheck;
        this.enrolledSiteId = enrolledSiteId;
        this.enrolledSiteRecord = [SELECT Id,Healthcare_Facility__c,Status__c,CRO_Research_Study__r.Research_Study__c,CRO_Research_Study__r.CRO_Account__c,
                                    CRO_Research_Study__c FROM Enrolled_Site__c WHERE Id=:enrolledSiteId];
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        if(this.isPreliminaryCheck){
            return Database.getQueryLocator([
                SELECT Id, Patient__c, Enrolled_Site__c, 
                Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c,
                Enrolled_Site__r.Healthcare_Facility__c,
                Enrolled_Site__r.CRO_Research_Study__r.CRO_Account__c,
                Enrolled_Site__r.CRO_Research_Study__c, Enrolled_Site__r.Status__c
                FROM Enrolled_Site_Research_Candidate__c
                WHERE Enrolled_Site__c = :enrolledSiteId AND Status__c = 'Initial Check'
                AND RecordType.DeveloperName = 'Pre_Enrolled']);
        }else{
            return Database.getQueryLocator([
                SELECT Id, Patient__c, Enrolled_Site__c,
                Enrolled_Site__r.CRO_Research_Study__r.Research_Study__c,
                Enrolled_Site__r.Healthcare_Facility__c,
                Enrolled_Site__r.CRO_Research_Study__r.CRO_Account__c,
                Enrolled_Site__r.CRO_Research_Study__c, Enrolled_Site__r.Status__c
                FROM Enrolled_Site_Research_Candidate__c 
                WHERE Enrolled_Site__c = :enrolledSiteId AND Status__c = 'Initial Check Cleared'
                AND RecordType.DeveloperName = 'Pre_Enrolled']);
        }
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Enrolled_Site_Research_Candidate__c> enrolledCandidateProcessed = new List<Enrolled_Site_Research_Candidate__c>();
        for (SObject recObj : scope) {
            if(this.isPreliminaryCheck){
                Enrolled_Site_Research_Candidate__c enrolledSiteCandidate = (Enrolled_Site_Research_Candidate__c) recObj;
                PatientAgentHeadlessController.checkPatientSiteEligibility(enrolledSiteCandidate,new Account(Id= enrolledSiteCandidate.Patient__c));
            }else{
                Enrolled_Site_Research_Candidate__c enrolledSiteCandidate = (Enrolled_Site_Research_Candidate__c) recObj;
                PatientAgentHeadlessController.checkPatientPCPEligibility(enrolledSiteCandidate,new Account(Id=enrolledSiteCandidate.Patient__c));
            }
        }
    } 

    public void finish(Database.BatchableContext bc) {
        if(this.isPreliminaryCheck){
            Id pcpAgentTaskRecordTypeId = SObjectType.Task.getRecordTypeInfosByDeveloperName().get('PCP_Agent_Task').getRecordTypeId();
            Task task = new Task(
                recordTypeId            = pcpAgentTaskRecordTypeId,
                Subject                 = 'Identify Shortlisted Patients',
                WhatId                  = this.enrolledSiteRecord.Id,
                Status                  = 'Open',
                Description             = 'Shortlist patients for mentioned research study.',
                Research_Study__c       = this.enrolledSiteRecord.CRO_Research_Study__r.Research_Study__c,
                Enrolled_Site__c        = this.enrolledSiteRecord.Id,
                Healthcare_Facility__c  = this.enrolledSiteRecord.Healthcare_Facility__c,
                CRO_Account__c          = this.enrolledSiteRecord.CRO_Research_Study__r.CRO_Account__c,
                CRO_Research_Study__c   = this.enrolledSiteRecord.CRO_Research_Study__c
            );
            insert task;
            
            //close the site agent task
            List<Task> siteAgentTaskList = new List<Task>();
            for(Task tsk : [SELECT Id, Status FROM Task WHERE WhatId = :enrolledSiteId AND RecordType.DeveloperName='Site_Agent_Task' AND Status='Open']){
                tsk.Status = 'Completed';
                siteAgentTaskList.add(tsk);
            }
            if(siteAgentTaskList.size()>0){
                update siteAgentTaskList;
            }
        } else {
            //create a task - CRO_Agent_Task
            Id croAgentTaskRecordTypeId = SObjectType.Task.getRecordTypeInfosByDeveloperName().get('CRO_Agent_Task').getRecordTypeId();
            Task task = new Task(
                recordTypeId            = croAgentTaskRecordTypeId,
                Subject                 = 'Identify Enrolled Patients',
                WhatId                  = this.enrolledSiteRecord.Id,
                Status                  = 'Open',
                Description             = 'Calculate eligiblity score for shortlisted patients.',
                Research_Study__c       = this.enrolledSiteRecord.CRO_Research_Study__r.Research_Study__c,
                Healthcare_Facility__c  = this.enrolledSiteRecord.Healthcare_Facility__c,
                Enrolled_Site__c        = this.enrolledSiteRecord.Id,
                CRO_Account__c          = this.enrolledSiteRecord.CRO_Research_Study__r.CRO_Account__c,
                CRO_Research_Study__c   = this.enrolledSiteRecord.CRO_Research_Study__c
            );
            insert task;

            List<Task> siteAgentTaskList = new List<Task>();
            for(Task tsk : [SELECT Id, Status FROM Task WHERE WhatId = :enrolledSiteId AND RecordType.DeveloperName='PCP_Agent_Task' AND Status='Open']){
                tsk.Status = 'Completed';
                siteAgentTaskList.add(tsk);
            }
            if(siteAgentTaskList.size()>0){
                update siteAgentTaskList;
            }
        }
    }
}