initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/CRO_Account__c.field-meta.xml
<CustomField>
    <fullName>CRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO_Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CRO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Research_Study__c.field-meta.xml
<CustomField>
    <fullName>Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Study</label>
    <referenceTo>Research_Study__c</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/DrugSiteEligibilityRunLog__c/DrugSiteEligibilityRunLog__c.object-meta.xml
<CustomObject>
    <description>it will capture the logs of drug site eligibility run</description>
    <label>Drug Site Eligibility Run Log</label>
    <nameField>
        <label>DrugSiteEligibilityRunLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Site Eligibility Run Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/DrugSiteEligibilityRunLog__c/fields/CRO_Agent_LLM_Repsonse__c.field-meta.xml
<CustomField>
    <fullName>CRO_Agent_LLM_Repsonse__c</fullName>
    <label>CRO Agent LLM Repsonse</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/DrugSiteEligibilityRunLog__c/fields/Enrolled_Site__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site__c</fullName>
    <label>Enrolled Site</label>
    <referenceTo>Enrolled_Site__c</referenceTo>
    <relationshipLabel>Drug Site Eligibility Run Logs</relationshipLabel>
    <relationshipName>Drug_Site_Eligibility_Run_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Agent_LLM_Response__c.field-meta.xml
<CustomField>
    <fullName>CRO_Agent_LLM_Response__c</fullName>
    <label>CRO Agent LLM Response</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Research_Study__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO Research Study</label>
    <referenceTo>CRO_Research_Study__c</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <referenceTo>HealthcareFacility</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Research_Study__c/Research_Study__c.object-meta.xml
<CustomObject>
    <label>Research Study</label>
    <nameField>
        <label>Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Research_Study__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Task/recordTypes/Site_Agent_Task.recordType-meta.xml
<RecordType>
    <fullName>Site_Agent_Task</fullName>
    <active>true</active>
    <label>Site Agent Task</label>
</RecordType>

initialSetup/main/default/classes/SiteAgentHeadlessController.cls
public class SiteAgentHeadlessController {
    
    public static String checkSiteEligibility(Enrolled_Site__c site, Research_Study__c researchStudy, CRO_Research_Study__c croRS){
        System.debug('User--->'+UserInfo.getUserId());
        HealthcareFacility facility =  new HealthcareFacility(Id = site.Healthcare_Facility__c);
        
        ConnectApi.WrappedValue inputResearchStudy = new ConnectApi.WrappedValue();
        inputResearchStudy.value = new Map<String, String> {'Id' => researchStudy.ID};
            
        ConnectApi.WrappedValue inputFacility = new ConnectApi.WrappedValue();
        inputFacility.value = new Map<String, String> {'Id' => facility.Id};  
            
        Map<String, ConnectApi.WrappedValue> inputParams = new Map<String, ConnectApi.WrappedValue>{};
        inputParams.put('Input:Research_Study',inputResearchStudy);
        inputParams.put('Input:Health_Care_Facility',inputFacility);
        
        system.debug('inputParams: '+inputParams);
        String result = PromptUtility.invokePrompt('Site_Eligiblility', inputParams);
        result = result.replace('\u00A0', ' ');
        System.debug('**Result***'+result);
        //write log run logic here 
        Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(result);
        // Cast values if you need them as String
        String response = (String) resultMap.get('Response');
        String status = (String) resultMap.get('Status');
        Enrolled_Site__c enrolledSite = new Enrolled_Site__c(Id=site.Id,CRO_Agent_LLM_Response__c = response,Status__c = status);
        update enrolledSite;
        //task - enrolledsite.status == Identified then task status completed
        //task trigger - task.status == completed ---> flow trigger --> site agent --> publish event 
        DrugSiteEligibilityRunLog__c log = new DrugSiteEligibilityRunLog__c(CRO_Agent_LLM_Repsonse__c = response, Enrolled_Site__c = enrolledSite.Id);
        insert log;
        
        Id siteAgentTaskRecordTypeId = SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Site_Agent_Task').getRecordTypeId();
        if(enrolledSite.Status__c == 'Identified' ) {
            Task task = new Task(
                recordTypeId = siteAgentTaskRecordTypeId,
                Subject = 'Identify Potential Patients',
                WhatId = enrolledSite.Id,
                Status = 'Open',
                Description = 'Identify potential patients for mentioned research study.',
                Research_Study__c = researchStudy.Id,
                Healthcare_Facility__c = facility.Id,
                CRO_Account__c = croRS.CRO_Account__c,
                CRO_Research_Study__c = croRS.Id,
                Enrolled_Site__c = enrolledSite.Id
            );
            
            insert task;
            System.debug(task.id);
        }
        
        return result;
    } 
}