initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Enrolled_Candidate_Count__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Candidate_Count__c</fullName>
    <label>Enrolled Candidate Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Research_Study__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO Research Study</label>
    <referenceTo>CRO_Research_Study__c</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/Enrolled_Site_Research_Candidate__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site Research Candidate</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Enrolled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site Research Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Eligibility_Score__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Score__c</fullName>
    <label>Eligibility Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site__c</fullName>
    <label>Enrolled Site</label>
    <referenceTo>Enrolled_Site__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site_Research_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Research_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolled Site Research Candidate</label>
    <referenceTo>Enrolled_Site_Research_Candidate__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Initial Check</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Trial In-Progress</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Initial Check Cleared</fullName>
            </value>
            <value>
                <fullName>Rejected After Shortlisted</fullName>
            </value>
            <value>
                <fullName>Initial Check Failed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Invite Sent for Enrollment</fullName>
            </value>
            <value>
                <fullName>Enrollment Accepted</fullName>
            </value>
            <value>
                <fullName>Enrollment Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Enrolled</fullName>
    <active>true</active>
    <label>Enrolled</label>
</RecordType>

initialSetup/main/default/classes/CandidateScoringHandler.cls
public class CandidateScoringHandler {

    public static void assignCandidateStatus(Id enrolledSiteId) {
        List<Enrolled_Site_Research_Candidate__c> candidates = [
            SELECT Id, Eligibility_Score__c, Status__c,Enrolled_Site__r.CRO_Research_Study__r.Enrolled_Candidate_Count__c 
            FROM Enrolled_Site_Research_Candidate__c 
            WHERE Enrolled_Site__c = :enrolledSiteId 
            AND Status__c = 'Shortlisted'
            AND Eligibility_Score__c != null
            AND RecordType.DeveloperName = 'Enrolled'
            ORDER BY Eligibility_Score__c DESC
        ];

        Integer enrolledCount = 0;
        for (Enrolled_Site_Research_Candidate__c cand : candidates) {
            Integer candidateCount = Integer.valueOf(cand.Enrolled_Site__r.CRO_Research_Study__r.Enrolled_Candidate_Count__c);
            if (cand.Eligibility_Score__c > 90) {
                cand.Status__c = 'Invite Sent for Enrollment';
                enrolledCount++;
            } else if (cand.Eligibility_Score__c > 70) {
                cand.Status__c = 'On Hold';
            } else {
                cand.Status__c = 'Rejected After Shortlisted';
            }
        }
        update candidates;
    }
}