initialSetup/main/default/objects/CRO_Research_Event__e/CRO_Research_Event__e.object-meta.xml
<CustomObject>
    <label>CRO Research Event</label>
    <pluralLabel>CRO Research Event</pluralLabel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Event__e/fields/CRO_Research_Study_ID__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study_ID__c</fullName>
    <label>CRO Research Study ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/CRO_Account__c.field-meta.xml
<CustomField>
    <fullName>CRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO_Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CRO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Research_Study__c.field-meta.xml
<CustomField>
    <fullName>Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Study</label>
    <referenceTo>Research_Study__c</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/CRO_Research_Study__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO Research Study</label>
    <referenceTo>CRO_Research_Study__c</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <referenceTo>HealthcareFacility</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/HealthcareFacility/fields/Count_of_Enrolled_Patients__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Enrolled_Patients__c</fullName>
    <label>Count of Enrolled Patients</label>
    <summaryFilterItems>
        <field>Patient_Site__c.Enrollment_Status__c</field>
        <operation>equals</operation>
        <value>Enrolled</value>
    </summaryFilterItems>
    <summaryForeignKey>Patient_Site__c.Healthcare_Facility__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

initialSetup/main/default/objects/Research_Study__c/Research_Study__c.object-meta.xml
<CustomObject>
    <label>Research Study</label>
    <nameField>
        <label>Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Research_Study__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/classes/CROResearchEventHandler.cls
/**
* @File Name : CROResearchEventHandler.cls
* @Description : Handler Class for CROResearchEventTrigger
* @Author : Pradeep Sharma
* @Last Modified By : Aakash Malik
* @Last Modified On : August 18, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | August 1, 2025 | Pradeep Sharma  | Initial Version
* 2.0 | August 18, 2025 | Aakash Malik        | Bulkified version
**/
public class CROResearchEventHandler {
   
    public static void afterInsert(List<CRO_Research_Event__e> croResearchEvents) {
        if (croResearchEvents.isEmpty()) return;

        Set<Id> researchStudyIds = new Set<Id>();
        for (CRO_Research_Event__e evt : croResearchEvents) {
            if (evt.CRO_Research_Study_ID__c != null) {
                researchStudyIds.add(evt.CRO_Research_Study_ID__c);
            }
        }

        if (researchStudyIds.isEmpty()) return;

        Map<Id, CRO_Research_Study__c> researchStudyMap = new Map<Id, CRO_Research_Study__c>([SELECT Id, Name, CRO_Account__c, Research_Study__c FROM CRO_Research_Study__c WHERE Id IN :researchStudyIds]);

        List<HealthcareFacility> facilities = [SELECT Id, Count_of_Enrolled_Patients__c FROM HealthcareFacility WHERE Count_of_Enrolled_Patients__c > 0 ];
        System.debug('Facilities count: ' + facilities.size());

        List<Enrolled_Site__c> enrolledSites = new List<Enrolled_Site__c>();

        for (Id researchStudyId : researchStudyMap.keySet()) {
            for (HealthcareFacility facility : facilities) {
                enrolledSites.add(new Enrolled_Site__c(
                    Healthcare_Facility__c = facility.Id,
                    CRO_Research_Study__c = researchStudyId,
                    Status__c = 'Invited for Survey'
                ));
            }
        }

        System.debug('Enrolled Sites to insert: ' + enrolledSites.size());

        if (!enrolledSites.isEmpty()) {
            insert enrolledSites;
        }

        for (Id researchStudyId : researchStudyIds) {
            Database.executeBatch(new SiteEligiblityPromptCallBatch(researchStudyId), 1);
        }
    }  
}