initialSetup/main/default/objects/Patient_Consent_Invite__c/Patient_Consent_Invite__c.object-meta.xml
<CustomObject>
    <label>Patient Consent Invite</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Patient Consent Invite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Consent Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Patient_Consent_Invite__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invite Sent for Enrollment</fullName>
            </value>
            <value>
                <fullName>Enrollment Accepted</fullName>
            </value>
            <value>
                <fullName>Enrollment Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/classes/PatientConsentController.cls
public with sharing class PatientConsentController {
    @AuraEnabled
    public static void updateEnrollmentStatus(Id recordId, String newStatus) {
        if(recordId == null || String.isBlank(newStatus)) {
            throw new AuraHandledException('Record Id or Status is missing');
        }

        Patient_Consent_Invite__c pci = [
            SELECT Id, Name, Status__c 
            FROM Patient_Consent_Invite__c 
            WHERE Id = :recordId
            LIMIT 1
        ];

        pci.Status__c = newStatus;
        update pci;
    }
    
}