initialSetup/main/default/objects/Account/recordTypes/CRO.recordType-meta.xml
<RecordType>
    <fullName>CRO</fullName>
    <active>true</active>
    <label>CRO</label>
</RecordType>

initialSetup/main/default/objects/CRO_Research_Event__e/CRO_Research_Event__e.object-meta.xml
<CustomObject>
    <label>CRO Research Event</label>
    <pluralLabel>CRO Research Event</pluralLabel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Event__e/fields/CRO_Research_Study_ID__c.field-meta.xml
<CustomField>
    <fullName>CRO_Research_Study_ID__c</fullName>
    <label>CRO Research Study ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/CRO_Research_Study__c.object-meta.xml
<CustomObject>
    <label>CRO Research Study</label>
    <nameField>
        <displayFormat>CRO-RS-{0000}</displayFormat>
        <label>CRO Research Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRO Research Study</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/CRO_Account__c.field-meta.xml
<CustomField>
    <fullName>CRO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRO_Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CRO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/CRO_Research_Study__c/fields/Research_Study__c.field-meta.xml
<CustomField>
    <fullName>Research_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Study</label>
    <referenceTo>Research_Study__c</referenceTo>
    <relationshipLabel>CRO Research Study</relationshipLabel>
    <relationshipName>CRO_Research_Study</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Research_Study__c/Research_Study__c.object-meta.xml
<CustomObject>
    <label>Research Study</label>
    <nameField>
        <label>Study Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/classes/Agent_CRO_ResearchStudyPublisher.cls
public without sharing class Agent_CRO_ResearchStudyPublisher {

    public class CRORequest {
        @InvocableVariable(required=true)
        public String researchStudyName;

        @InvocableVariable(required=true)
        public String croName;
    }

    public class CROResponse {
        @InvocableVariable public String responseJson;
    }

    @InvocableMethod(label='Publish CRO Research Events' description='Publishes Platform Event for given CRO and Research Study')
    public static List<CROResponse> publishResearchEvent(List<CRORequest> requests) {
        List<CROResponse> responses = new List<CROResponse>();

        for (CRORequest req : requests) {
            Map<String, Object> result = new Map<String, Object>();
            CROResponse resp = new CROResponse();

            try {
                Research_Study__c study = [SELECT Id, Name FROM Research_Study__c WHERE Name = :req.researchStudyName LIMIT 1];

                Account croAcc = [SELECT Id, Name FROM Account WHERE Name = :req.croName LIMIT 1];

                CRO_Research_Study__c croStudy;
                List<CRO_Research_Study__c> existing = [SELECT Id FROM CRO_Research_Study__c WHERE Research_Study__c = :study.Id AND CRO_Account__c = :croAcc.Id LIMIT 1];

                if (!existing.isEmpty()) {
                    croStudy = existing[0];
                } else {
                    croStudy = new CRO_Research_Study__c(Research_Study__c = study.Id, CRO_Account__c = croAcc.Id);
                    insert croStudy;
                }

                CRO_Research_Event__e evt = new CRO_Research_Event__e(CRO_Research_Study_ID__c = croStudy.Id);

                List<Database.SaveResult> results = EventBus.publish(new List<CRO_Research_Event__e>{ evt });

                if (!results.isEmpty() && results[0].isSuccess()) {
                    result.put('message', 'The eligibility check for ' + req.researchStudyName + ' with CRO ' + req.croName + ' has started. Eligible sites will be available soon.');
                    result.put('researchStudyId', study.Id);
                    result.put('researchStudyName', req.researchStudyName);
                } else {
                    result.put('message', 'Failed to publish event');
                    if (!results.isEmpty()) {
                        result.put('error', results[0].getErrors()[0].getMessage());
                    }
                }

            } catch (Exception e) {
                result.put('message', 'Error processing request for: ' + req.researchStudyName + ' with CRO ' + req.croName);
                result.put('error', e.getMessage());
            }

            resp.responseJson = JSON.serialize(result);
            responses.add(resp);
        }

        return responses;
    }
}