initialSetup/main/default/objects/Enrolled_Site__c/Enrolled_Site__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Enrolled Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcare Facility</label>
    <referenceTo>HealthcareFacility</referenceTo>
    <relationshipLabel>Enrolled Site</relationshipLabel>
    <relationshipName>Enrolled_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
            </value>
            <value>
                <fullName>Invited for Survey</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Recruitment Ongoing</fullName>
            </value>
            <value>
                <fullName>Recruitment Closed</fullName>
            </value>
            <value>
                <fullName>Trial Upcoming</fullName>
            </value>
            <value>
                <fullName>Trial Ongoing</fullName>
            </value>
            <value>
                <fullName>Trial Completed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/Enrolled_Site_Research_Candidate__c.object-meta.xml
<CustomObject>
    <label>Enrolled Site Research Candidate</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Enrolled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Site Research Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Eligibility_Check_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Check_Stage__c</fullName>
    <label>Eligibility Check Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site__c</fullName>
    <label>Enrolled Site</label>
    <referenceTo>Enrolled_Site__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Enrolled_Site_Research_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Research_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolled Site Research Candidate</label>
    <referenceTo>Enrolled_Site_Research_Candidate__c</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolled_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Patient_Email__c.field-meta.xml
<CustomField>
    <fullName>Patient_Email__c</fullName>
    <label>Patient Email</label>
    <type>Email</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/PCP__c.field-meta.xml
<CustomField>
    <fullName>PCP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PCP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolled Site Research Candidates (PCP)</relationshipLabel>
    <relationshipName>Enrolled_Site_Research_Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Initial Check</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Trial In-Progress</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Initial Check Cleared</fullName>
            </value>
            <value>
                <fullName>Rejected After Shortlisted</fullName>
            </value>
            <value>
                <fullName>Initial Check Failed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Invite Sent for Enrollment</fullName>
            </value>
            <value>
                <fullName>Enrollment Accepted</fullName>
            </value>
            <value>
                <fullName>Enrollment Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Enrolled</fullName>
    <active>true</active>
    <label>Enrolled</label>
</RecordType>

initialSetup/main/default/objects/Enrolled_Site_Research_Candidate__c/recordTypes/Pre_Enrolled.recordType-meta.xml
<RecordType>
    <fullName>Pre_Enrolled</fullName>
    <active>true</active>
    <label>Pre-Enrolled</label>
</RecordType>

initialSetup/main/default/objects/HealthcareFacility/fields/Count_of_Enrolled_Patients__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Enrolled_Patients__c</fullName>
    <label>Count of Enrolled Patients</label>
    <summaryFilterItems>
        <field>Patient_Site__c.Enrollment_Status__c</field>
        <operation>equals</operation>
        <value>Enrolled</value>
    </summaryFilterItems>
    <summaryForeignKey>Patient_Site__c.Healthcare_Facility__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

initialSetup/main/default/objects/Patient_Eligibility_Event__e/Patient_Eligibility_Event__e.object-meta.xml
<CustomObject>
    <label>Patient Eligibility Event</label>
    <pluralLabel>Patient Eligibility Events</pluralLabel>
</CustomObject>

initialSetup/main/default/objects/Patient_Eligibility_Event__e/fields/Eligibility_Check_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Check_Stage__c</fullName>
    <label>Eligibility Check Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/Patient_Eligibility_Event__e/fields/Enrolled_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_Id__c</fullName>
    <label>Enrolled Site Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/Patient_Eligibility_Event_Tracker__c/Patient_Eligibility_Event_Tracker__c.object-meta.xml
<CustomObject>
    <label>Patient Eligibility Event Tracker</label>
    <nameField>
        <label>Patient Eligibility Event Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Eligibility Event Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Patient_Eligibility_Event_Tracker__c/fields/Enrolled_Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Site_ID__c</fullName>
    <label>Enrolled Site ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

initialSetup/main/default/objects/Patient_Site__c/Patient_Site__c.object-meta.xml
<CustomObject>
    <label>Patient Site</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Patient Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

initialSetup/main/default/objects/Patient_Site__c/fields/Healthcare_Facility__c.field-meta.xml
<CustomField>
    <fullName>Healthcare_Facility__c</fullName>
    <label>Healthcare Facility</label>
    <referenceTo>HealthcareFacility</referenceTo>
    <relationshipLabel>Patient Sites</relationshipLabel>
    <relationshipName>Patient_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

initialSetup/main/default/objects/Patient_Site__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Sites</relationshipLabel>
    <relationshipName>Patient_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/objects/Patient_Site__c/fields/PCP__c.field-meta.xml
<CustomField>
    <fullName>PCP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PCP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Sites (PCP)</relationshipLabel>
    <relationshipName>Patient_Sites1</relationshipName>
    <type>Lookup</type>
</CustomField>

initialSetup/main/default/classes/PatientEligibilityEventTriggerHandler.cls
public class PatientEligibilityEventTriggerHandler {
    public static void afterInsert(List<Patient_Eligibility_Event__e> patientEligibilityEvents) { 
        System.debug('Events received: ' + patientEligibilityEvents.size());
        // 1️⃣ Track all events
        Set<Id> siteAgentEnrolledSiteIds = new Set<Id>();
        Set<Id> pcpAgentEnrolledSiteIds = new Set<Id>();

        List<Patient_Eligibility_Event_Tracker__c> eventTrackerList = new List<Patient_Eligibility_Event_Tracker__c>();
        for (Patient_Eligibility_Event__e evt : patientEligibilityEvents) {
            eventTrackerList.add(new Patient_Eligibility_Event_Tracker__c(
                Enrolled_Site_ID__c = evt.Enrolled_Site_Id__c,
                Eligibility_Check_Stage__c = evt.Eligibility_Check_Stage__c
            ));
            if (evt.Enrolled_Site_Id__c != null && evt.Eligibility_Check_Stage__c == 'Site Agent') {
                siteAgentEnrolledSiteIds.add(evt.Enrolled_Site_Id__c);
            } else if(evt.Enrolled_Site_Id__c != null && evt.Eligibility_Check_Stage__c == 'PCP Agent') {
                pcpAgentEnrolledSiteIds.add(evt.Enrolled_Site_Id__c);
            }
        }

        if(!eventTrackerList.isEmpty()) {
            insert eventTrackerList;
        }

        if(!pcpAgentEnrolledSiteIds.isEmpty()) {
            for(Id eachSiteId : pcpAgentEnrolledSiteIds){
                Database.executeBatch(new PatientEligibilityPromptCallBatch(eachSiteId, false),1);
            }
        }
        
        if(!siteAgentEnrolledSiteIds.isEmpty()) {
            Map<Id, Id> enrolledSiteFacilityMap = new Map<Id, Id>();
            for(Enrolled_Site__c eachEnrolledSite : [SELECT Id, Healthcare_Facility__c FROM Enrolled_Site__c WHERE Id IN :siteAgentEnrolledSiteIds]) {
                enrolledSiteFacilityMap.put(eachEnrolledSite.Id, eachEnrolledSite.Healthcare_Facility__c);
            }
            
            Map<Id, List<Patient_Site__c>> healthSitePatientMap = new Map<Id, List<Patient_Site__c>>();
            for(Patient_Site__c eachPatientSite : [SELECT Id,Patient__c,Patient__r.PersonEmail,Healthcare_Facility__c,PCP__c FROM Patient_Site__c WHERE Healthcare_Facility__c = :enrolledSiteFacilityMap.values()
                                                    AND Healthcare_Facility__r.Count_of_Enrolled_Patients__c > 0]) {
                if(!healthSitePatientMap.containsKey(eachPatientSite.Healthcare_Facility__c)) {
                    healthSitePatientMap.put(eachPatientSite.Healthcare_Facility__c, new List<Patient_Site__c>());
                }
                healthSitePatientMap.get(eachPatientSite.Healthcare_Facility__c).add(eachPatientSite);
            }

            // 4️⃣ Get the Pre-Enrolled Record Type Id once
            Id preEnrolledRecordTypeId = SObjectType.Enrolled_Site_Research_Candidate__c
                .getRecordTypeInfosByDeveloperName()
                .get('Pre_Enrolled')
                .getRecordTypeId();
            List<Enrolled_Site_Research_Candidate__c> enrolledSiteCandidateList = new List<Enrolled_Site_Research_Candidate__c>();
            for(Id enrolledSiteKey : enrolledSiteFacilityMap.keySet()) {
                Id healthcareFacilityId = enrolledSiteFacilityMap.get(enrolledSiteKey);
                for(Patient_Site__c patientSite : healthSitePatientMap.get(healthcareFacilityId)) {
                    enrolledSiteCandidateList.add(new Enrolled_Site_Research_Candidate__c(
                        Patient__c = patientSite.Patient__c,
                        Patient_Email__c = patientSite.Patient__r.PersonEmail,
                        Enrolled_Site__c = enrolledSiteKey,
                        RecordTypeId = preEnrolledRecordTypeId,
                        Status__c = 'Initial Check',
                        PCP__c   = patientSite.PCP__c
                    ));
                }
            }

            // 6️⃣ Insert all candidates in one go
            if (!enrolledSiteCandidateList.isEmpty()) {
                insert enrolledSiteCandidateList;
                System.debug('Inserted Candidates: ' + enrolledSiteCandidateList.size());
            }
            
            for(Id eachSiteId : siteAgentEnrolledSiteIds){
                Database.executeBatch(new PatientEligibilityPromptCallBatch(eachSiteId, true),1);
            }
        }
    }
}